# +----------------------+
# |    DIRECTORY PATH    |
# +----------------------+

data_dir : 
  data   : /pclhcb06/landerli/TurCal
  simu   : /home/mabarbet/PythonFastSim/data

model_dir : /home/mabarbet/PythonFastSim/trainings/pidsim/models

class_dir : /home/mabarbet/PythonFastSim/trainings/pidsim/models

report_dir : /home/mabarbet/PythonFastSim/trainings/pidsim/reports
