# +--------------+
# |    ISMUON    |
# +--------------+
isMuon:
  #  Muon
  # ------
  Muon:
    # <-- 2016 Mag Up -->
    2016MagUp:
      chunk_size : 10000000   # 60 mln
      loss : deviance
      learning_rate : 0.039
      n_estimators  : 131
      criterion : squared_error
      min_samples_leaf : 10
      max_depth : 12
      validation_split : 0.5
    # <-- 2016 Mag Down -->
    2016MagDown:
  #  Pion
  # ------
  Pion:
    # <-- 2016 Mag Up -->
    2016MagUp:
      chunk_size : 20000000   # 150 mln
      loss : deviance
      learning_rate : 0.024
      n_estimators  : 142
      criterion : squared_error
      min_samples_leaf : 1
      max_depth : 10
      validation_split : 0.5
    # <-- 2016 Mag Down -->
    2016MagDown:
  #  Kaon
  # ------
  Kaon:
    # <-- 2016 Mag Up -->
    2016MagUp:
      chunk_size : 20000000   # 150 mln
      loss : deviance
      learning_rate : 0.129
      n_estimators  : 149
      criterion : friedman_mse
      min_samples_leaf : 50
      max_depth : 3
      validation_split : 0.5
    # <-- 2016 Mag Down -->
    2016MagDown:
  #  Proton
  # --------
  Proton:
    # <-- 2016 Mag Up -->
    2016MagUp:
      chunk_size : 50000000   # 105 mln
      loss : deviance
      learning_rate : 0.131
      n_estimators  : 115
      criterion : friedman_mse
      min_samples_leaf : 50
      max_depth : 7
      validation_split : 0.5
    # <-- 2016 Mag Down -->
    2016MagDown: