# +--------------+
# |    ISMUON    |
# +--------------+
isMuon:
  #  Muon
  # ------
  Muon:
    # <-- 2016 Mag Up -->
    2016MagUp:
      chunk_size : 5000000   # 60 mln
      X_preprocessing : quantile
      loss : deviance
      learning_rate : 0.214126
      n_estimators  : 26
      criterion : friedman_mse
      min_samples_leaf : 1
      max_depth : 11
      validation_split : 0.5
    # <-- 2016 Mag Down -->
    2016MagDown:
  #  Pion
  # ------
  Pion:
    # <-- 2016 Mag Up -->
    2016MagUp:
      chunk_size : 15000000   # 150 mln
      X_preprocessing : quantile
      loss : deviance
      learning_rate : 0.165529
      n_estimators  : 14
      criterion : squared_error
      min_samples_leaf : 1
      max_depth : 9
      validation_split : 0.5
    # <-- 2016 Mag Down -->
    2016MagDown:
  #  Kaon
  # ------
  Kaon:
    # <-- 2016 Mag Up -->
    2016MagUp:
      chunk_size : 15000000   # 150 mln
      X_preprocessing : quantile
      loss : deviance
      learning_rate : 0.350986
      n_estimators  : 20
      criterion : friedman_mse
      min_samples_leaf : 1
      max_depth : 15
      validation_split : 0.5
    # <-- 2016 Mag Down -->
    2016MagDown:
  #  Proton
  # --------
  Proton:
    # <-- 2016 Mag Up -->
    2016MagUp:
      chunk_size : 50000000   # 105 mln
      X_preprocessing : quantile
      loss : deviance
      learning_rate : 0.270504
      n_estimators  : 9
      criterion : friedman_mse
      min_samples_leaf : 1
      max_depth : 8
      validation_split : 0.5
    # <-- 2016 Mag Down -->
    2016MagDown: