# ==========================================================================================
standard:
# ==========================================================================================

  # +------------+
  # |    MUON    |
  # +------------+
  Muon:

    # <---- | Calib samples | 2016 Mag Up | ---->
    2016-MagUp-data:
      chunk_size : 5000000   # 60 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.000025
      g_lr : 0.000025
      d_updt_per_batch : 5
      g_updt_per_batch : 1
      grad_penalty : 10.0
      lr_sched_factor : 0.95
      lr_sched_step : 10
      batch_size : 512
      num_epochs : 100
      validation_split : 0.2

    # <---- | Calib samples | 2016 Mag Down | ---->
    2016-MagDown-data:

  # +------------+
  # |    PION    |
  # +------------+
  Pion:

    # <---- | Calib samples | 2016 Mag Up | ---->
    2016-MagUp-data:
      chunk_size : 5000000   # 150 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.000025
      g_lr : 0.000025
      d_updt_per_batch : 5
      g_updt_per_batch : 1
      grad_penalty : 10.0
      lr_sched_factor : 0.95
      lr_sched_step : 10
      batch_size : 512
      num_epochs : 100
      validation_split : 0.2

    # <---- | Calib samples | 2016 Mag Down | ---->
    2016-MagDown-data:

  # +------------+
  # |    KAON    |
  # +------------+
  Kaon:

    # <---- | Calib samples | 2016 Mag Up | ---->
    2016-MagUp-data:
      chunk_size : 5000000   # 150 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.000025
      g_lr : 0.000025
      d_updt_per_batch : 5
      g_updt_per_batch : 1
      grad_penalty : 10.0
      lr_sched_factor : 0.95
      lr_sched_step : 10
      batch_size : 512
      num_epochs : 100
      validation_split : 0.2

    # <---- | Calib samples | 2016 Mag Down | ---->
    2016-MagDown-data:

  # +--------------+
  # |    PROTON    |
  # +--------------+
  Proton:
    # <---- | Calib samples | 2016 Mag Up | ---->
    2016-MagUp-data:
      chunk_size : 5000000   # 105 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.000025
      g_lr : 0.000025
      d_updt_per_batch : 5
      g_updt_per_batch : 1
      grad_penalty : 10.0
      lr_sched_factor : 0.95
      lr_sched_step : 10
      batch_size : 512
      num_epochs : 100
      validation_split : 0.2
  
    # <---- | Calib samples | 2016 Mag Down | ---->
    2016-MagDown-data:

# ==========================================================================================
base:
# ==========================================================================================

  # +------------+
  # |    MUON    |
  # +------------+
  Muon:

    # <---- | Calib samples | 2016 Mag Up | ---->
    2016-MagUp-data:
      chunk_size : 5000000   # 60 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.000025
      g_lr : 0.000025
      d_updt_per_batch : 5
      g_updt_per_batch : 1
      grad_penalty : 10.0
      lr_sched_factor : 0.95
      lr_sched_step : 10
      batch_size : 512
      num_epochs : 100
      validation_split : 0.2

    # <---- | Simu samples | 2016 Mag Up | ---->
    2016-MagUp-simu:
      chunk_size : 5000000   # 18 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 10
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.00004
      g_lr : 0.00002
      d_updt_per_batch : 5
      g_updt_per_batch : 1
      grad_penalty : 1.0
      lr_sched_factor : 0.95
      lr_sched_step : 10
      batch_size : 512
      num_epochs : 200
      validation_split : 0.2

    # <---- | Calib samples | 2016 Mag Down | ---->
    2016-MagDown-data:

    # <---- | Simu samples | 2016 Mag Down | ---->
    2016-MagDown-simu:

  # +------------+
  # |    PION    |
  # +------------+
  Pion:

    # <---- | Calib samples | 2016 Mag Up | ---->
    2016-MagUp-data:
      chunk_size : 5000000   # 150 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.000025
      g_lr : 0.000025
      d_updt_per_batch : 5
      g_updt_per_batch : 1
      grad_penalty : 10.0
      lr_sched_factor : 0.95
      lr_sched_step : 10
      batch_size : 512
      num_epochs : 100
      validation_split : 0.2

    # <---- | Simu samples | 2016 Mag Up | ---->
    2016-MagUp-simu:
      chunk_size : 5000000   # 150 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.00005
      g_lr : 0.00003
      d_updt_per_batch : 5
      g_updt_per_batch : 1
      grad_penalty : 1.0
      lr_sched_factor : 0.95
      lr_sched_step : 10
      batch_size : 512
      num_epochs : 100
      validation_split : 0.2

    # <---- | Calib samples | 2016 Mag Down | ---->
    2016-MagDown-data:

    # <---- | Simu samples | 2016 Mag Down | ---->
    2016-MagDown-simu:

  # +------------+
  # |    KAON    |
  # +------------+
  Kaon:

    # <---- | Calib samples | 2016 Mag Up | ---->
    2016-MagUp-data:
      chunk_size : 5000000   # 150 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.000025
      g_lr : 0.000025
      d_updt_per_batch : 5
      g_updt_per_batch : 1
      grad_penalty : 10.0
      lr_sched_factor : 0.95
      lr_sched_step : 10
      batch_size : 512
      num_epochs : 100
      validation_split : 0.2

    # <---- | Simu samples | 2016 Mag Up | ---->
    2016-MagUp-simu:
      chunk_size : 5000000   # 40 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.00004
      g_lr : 0.00002
      d_updt_per_batch : 5
      g_updt_per_batch : 1
      grad_penalty : 1.0
      lr_sched_factor : 0.95
      lr_sched_step : 10
      batch_size : 512
      num_epochs : 100
      validation_split : 0.2

    # <---- | Calib samples | 2016 Mag Down | ---->
    2016-MagDown-data:

    # <---- | Simu samples | 2016 Mag Down | ---->
    2016-MagDown-simu:

  # +--------------+
  # |    PROTON    |
  # +--------------+
  Proton:
    # <---- | Calib samples | 2016 Mag Up | ---->
    2016-MagUp-data:
      chunk_size : 5000000   # 105 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.000025
      g_lr : 0.000025
      d_updt_per_batch : 5
      g_updt_per_batch : 1
      grad_penalty : 10.0
      lr_sched_factor : 0.95
      lr_sched_step : 10
      batch_size : 512
      num_epochs : 100
      validation_split : 0.2
    
    # <---- | Simu samples | 2016 Mag Up | ---->
    2016-MagUp-simu:
      chunk_size : 5000000   # 30 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.000025
      g_lr : 0.000025
      d_updt_per_batch : 5
      g_updt_per_batch : 1
      grad_penalty : 10.0
      lr_sched_factor : 0.95
      lr_sched_step : 10
      batch_size : 512
      num_epochs : 100
      validation_split : 0.2

    # <---- | Calib samples | 2016 Mag Down | ---->
    2016-MagDown-data:

    # <---- | Simu samples | 2016 Mag Down | ---->
    2016-MagDown-simu: