# +------------+
# |    MUON    |
# +------------+
Muon:

  # <---- | Calib samples | 2016 Mag Up | ---->
  2016-MagUp-data:
    chunk_size : 10000000   # 60 mln
    loss : log_loss
    learning_rate : 0.402
    n_estimators  : 75
    criterion : squared_error
    min_samples_leaf : 10
    max_depth : 14
    validation_split : 0.5

  # <---- | Simu samples | 2016 Mag Up | ---->
  2016-MagUp-simu:
    chunk_size : 10000000   # 18 mln
    loss : log_loss
    learning_rate : 0.402
    n_estimators  : 75
    criterion : squared_error
    min_samples_leaf : 10
    max_depth : 14
    validation_split : 0.5

  # <---- | Calib samples | 2016 Mag Down | ---->
  2016-MagDown-data:

  # <---- | Simu samples | 2016 Mag Down | ---->
  2016-MagDown-simu:

# +------------+
# |    PION    |
# +------------+
Pion:

  # <---- | Calib samples | 2016 Mag Up | ---->
  2016-MagUp-data:
    chunk_size : 20000000   # 150 mln
    loss : log_loss
    learning_rate : 0.024
    n_estimators  : 142
    criterion : squared_error
    min_samples_leaf : 1
    max_depth : 10
    validation_split : 0.5

  # <---- | Simu samples | 2016 Mag Up | ---->
  2016-MagUp-simu:
    chunk_size : 20000000   # 150 mln
    loss : log_loss
    learning_rate : 0.024
    n_estimators  : 142
    criterion : squared_error
    min_samples_leaf : 1
    max_depth : 10
    validation_split : 0.5

  # <---- | Calib samples | 2016 Mag Down | ---->
  2016-MagDown-data:

  # <---- | Simu samples | 2016 Mag Down | ---->
  2016-MagDown-simu:

# +------------+
# |    KAON    |
# +------------+
Kaon:

  # <---- | Calib samples | 2016 Mag Up | ---->
  2016-MagUp-data:
    chunk_size : 20000000   # 150 mln
    loss : log_loss
    learning_rate : 0.129
    n_estimators  : 149
    criterion : friedman_mse
    min_samples_leaf : 50
    max_depth : 3
    validation_split : 0.5

  # <---- | Simu samples | 2016 Mag Up | ---->
  2016-MagUp-simu:
    chunk_size : 20000000   # 40 mln
    loss : log_loss
    learning_rate : 0.129
    n_estimators  : 149
    criterion : friedman_mse
    min_samples_leaf : 50
    max_depth : 3
    validation_split : 0.5

  # <---- | Calib samples | 2016 Mag Down | ---->
  2016-MagDown-data:

  # <---- | Simu samples | 2016 Mag Down | ---->
  2016-MagDown-simu:

# +--------------+
# |    PROTON    |
# +--------------+
Proton:

  # <---- | Calib samples | 2016 Mag Up | ---->
  2016-MagUp-data:
    chunk_size : 50000000   # 105 mln
    loss : log_loss
    learning_rate : 0.131
    n_estimators  : 115
    criterion : friedman_mse
    min_samples_leaf : 50
    max_depth : 7
    validation_split : 0.5

  # <---- | Simu samples | 2016 Mag Up | ---->
  2016-MagUp-simu:   
    chunk_size : null   # 30 mln
    loss : log_loss
    learning_rate : 0.131
    n_estimators  : 115
    criterion : friedman_mse
    min_samples_leaf : 50
    max_depth : 7
    validation_split : 0.5

  # <---- | Calib samples | 2016 Mag Down | ---->
  2016-MagDown-data:

  # <---- | Simu samples | 2016 Mag Down | ---->
  2016-MagDown-simu: