# ==========================================================================================
standard:
# ==========================================================================================

  # +------------+
  # |    MUON    |
  # +------------+
  Muon:

    # <---- | Calib samples | 2016 Mag Up | ---->
    2016-MagUp-data:

    # <---- | Calib samples | 2016 Mag Down | ---->
    2016-MagDown-data:

  # +------------+
  # |    PION    |
  # +------------+
  Pion:

    # <---- | Calib samples | 2016 Mag Up | ---->
    2016-MagUp-data:

    # <---- | Calib samples | 2016 Mag Down | ---->
    2016-MagDown-data:

  # +------------+
  # |    KAON    |
  # +------------+
  Kaon:

    # <---- | Calib samples | 2016 Mag Up | ---->
    2016-MagUp-data:
      chunk_size : 5000000   # 150 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      d_lr : 0.00005
      g_lr : 0.00005
      d_updt_per_batch : 1
      g_updt_per_batch : 1
      lr_sched_factor : 0.900
      lr_sched_step : 4
      batch_size : 512
      num_epochs : 200
      validation_split : 0.2

    # <---- | Calib samples | 2016 Mag Down | ---->
    2016-MagDown-data:

  # +--------------+
  # |    PROTON    |
  # +--------------+
  Proton:
    # <---- | Calib samples | 2016 Mag Up | ---->
    2016-MagUp-data:

    # <---- | Calib samples | 2016 Mag Down | ---->
    2016-MagDown-data:

# ==========================================================================================
base:
# ==========================================================================================

  # +------------+
  # |    MUON    |
  # +------------+
  Muon:

    # <---- | Calib samples | 2016 Mag Up | ---->
    2016-MagUp-data:

    # <---- | Simu samples | 2016 Mag Up | ---->
    2016-MagUp-simu:

    # <---- | Calib samples | 2016 Mag Down | ---->
    2016-MagDown-data:

    # <---- | Simu samples | 2016 Mag Down | ---->
    2016-MagDown-simu:

  # +------------+
  # |    PION    |
  # +------------+
  Pion:

    # <---- | Calib samples | 2016 Mag Up | ---->
    2016-MagUp-data:

    # <---- | Simu samples | 2016 Mag Up | ---->
    2016-MagUp-simu:

    # <---- | Calib samples | 2016 Mag Down | ---->
    2016-MagDown-data:

    # <---- | Simu samples | 2016 Mag Down | ---->
    2016-MagDown-simu:

  # +------------+
  # |    KAON    |
  # +------------+
  Kaon:

    # <---- | Calib samples | 2016 Mag Up | ---->
    2016-MagUp-data:
      chunk_size : 5000000   # 150 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      d_lr : 0.00005
      g_lr : 0.00005
      d_updt_per_batch : 1
      g_updt_per_batch : 1
      lr_sched_factor : 0.900
      lr_sched_step : 4
      batch_size : 512
      num_epochs : 200
      validation_split : 0.2

    # <---- | Simu samples | 2016 Mag Up | ---->
    2016-MagUp-simu:

    # <---- | Calib samples | 2016 Mag Down | ---->
    2016-MagDown-data:

    # <---- | Simu samples | 2016 Mag Down | ---->
    2016-MagDown-simu:

  # +--------------+
  # |    PROTON    |
  # +--------------+
  Proton:
    # <---- | Calib samples | 2016 Mag Up | ---->
    2016-MagUp-data:
    
    # <---- | Simu samples | 2016 Mag Up | ---->
    2016-MagUp-simu:

    # <---- | Calib samples | 2016 Mag Down | ---->
    2016-MagDown-data:

    # <---- | Simu samples | 2016 Mag Down | ---->
    2016-MagDown-simu:

# ==========================================================================================
tuning:
# ==========================================================================================

  # +------------+
  # |    MUON    |
  # +------------+
  Muon:

    # <---- | Calib samples | 2016 Mag Up | ---->
    2016-MagUp-data:
      chunk_size : 5000000   # 60 mln
      fine_tuned_d_layers : 6
      add_d_num_layers    : 1
      add_d_num_nodes     : 128
      add_d_alpha_leaky   : 0.05
      fine_tuned_g_layers : 6
      add_g_num_layers    : 1
      add_g_num_nodes     : 32
      add_g_alpha_leaky   : 0.05
      latent_dim : 64
      d_lr : 0.00003
      g_lr : 0.00002
      d_updt_per_batch : 3
      g_updt_per_batch : 1
      lr_sched_factor : 0.95
      lr_sched_step : 10
      batch_size : 512
      num_epochs : 200
      validation_split : 0.2

    # <---- | Simu samples | 2016 Mag Up | ---->
    2016-MagUp-simu:

    # <---- | Calib samples | 2016 Mag Down | ---->
    2016-MagDown-data:

    # <---- | Simu samples | 2016 Mag Down | ---->
    2016-MagDown-simu:

  # +------------+
  # |    PION    |
  # +------------+
  Pion:

    # <---- | Calib samples | 2016 Mag Up | ---->
    2016-MagUp-data:
      chunk_size : 5000000   # 150 mln
      fine_tuned_d_layers : 6
      add_d_num_layers    : 0
      add_d_num_nodes     : null
      add_d_alpha_leaky   : null
      fine_tuned_g_layers : 3
      add_g_num_layers    : 0
      add_g_num_nodes     : null
      add_g_alpha_leaky   : null
      latent_dim : 64
      d_lr : 0.00002
      g_lr : 0.00005
      d_updt_per_batch : 5
      g_updt_per_batch : 1
      lr_sched_factor : 0.95
      lr_sched_step : 10
      batch_size : 512
      num_epochs : 100
      validation_split : 0.2

    # <---- | Simu samples | 2016 Mag Up | ---->
    2016-MagUp-simu:

    # <---- | Calib samples | 2016 Mag Down | ---->
    2016-MagDown-data:

    # <---- | Simu samples | 2016 Mag Down | ---->
    2016-MagDown-simu:

  # +------------+
  # |    KAON    |
  # +------------+
  Kaon:

    # <---- | Calib samples | 2016 Mag Up | ---->
    2016-MagUp-data:
      chunk_size : 5000000   # 150 mln
      fine_tuned_d_layers : 2
      add_d_num_layers    : 1
      add_d_num_nodes     : 128
      add_d_alpha_leaky   : 0.05
      fine_tuned_g_layers : 6
      add_g_num_layers    : 0
      add_g_num_nodes     : null
      add_g_alpha_leaky   : null
      latent_dim : 64
      d_lr : 0.00003
      g_lr : 0.00002
      d_updt_per_batch : 5
      g_updt_per_batch : 1
      lr_sched_factor : 0.95
      lr_sched_step : 10
      batch_size : 512
      num_epochs : 200
      validation_split : 0.2

    # <---- | Simu samples | 2016 Mag Up | ---->
    2016-MagUp-simu:

    # <---- | Calib samples | 2016 Mag Down | ---->
    2016-MagDown-data:

    # <---- | Simu samples | 2016 Mag Down | ---->
    2016-MagDown-simu:

  # +--------------+
  # |    PROTON    |
  # +--------------+
  Proton:
    # <---- | Calib samples | 2016 Mag Up | ---->
    2016-MagUp-data:
      chunk_size : 5000000   # 105 mln
      fine_tuned_d_layers : 4
      add_d_num_layers    : 0
      add_d_num_nodes     : null
      add_d_alpha_leaky   : null
      fine_tuned_g_layers : 3
      add_g_num_layers    : 0
      add_g_num_nodes     : null
      add_g_alpha_leaky   : null
      latent_dim : 64
      d_lr : 0.00003
      g_lr : 0.00002
      d_updt_per_batch : 5
      g_updt_per_batch : 1
      lr_sched_factor : 0.95
      lr_sched_step : 10
      batch_size : 512
      num_epochs : 100
      validation_split : 0.2
    
    # <---- | Simu samples | 2016 Mag Up | ---->
    2016-MagUp-simu:

    # <---- | Calib samples | 2016 Mag Down | ---->
    2016-MagDown-data:

    # <---- | Simu samples | 2016 Mag Down | ---->
    2016-MagDown-simu: