# +------------+
# |    RICH    |
# +------------+
Rich:
  #  Muon
  # ------
  Muon:
    # <-- 2016 Mag Up -->
    2016MagUp:
    # <-- 2016 Mag Down -->
    2016MagDown:
  #  Pion
  # ------
  Pion:
    # <-- 2016 Mag Up -->
    2016MagUp:
    # <-- 2016 Mag Down -->
    2016MagDown:
  #  Kaon
  # ------
  Kaon:
    # <-- 2016 Mag Up -->
    2016MagUp:
      chunk_size : 500000   # 150 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      add_g_num_layers  : 0
      add_g_num_nodes   : 128
      add_g_alpha_leaky : 0.05
      latent_dim : 64
      d_lr : 0.00001
      g_lr : 0.000005
      d_updt_per_batch : 3
      g_updt_per_batch : 1
      lr_sched_factor : 0.900
      lr_sched_step : 10
      batch_size : 512
      num_epochs : 100
      validation_split : 0.2
    # <-- 2016 Mag Down -->
    2016MagDown:
  #  Proton
  # --------
  Proton:
    # <-- 2016 Mag Up -->
    2016MagUp:
    # <-- 2016 Mag Down -->
    2016MagDown:

# +------------+
# |    MUON    |
# +------------+
Muon:
  #  Muon
  # ------
  Muon:
    # <-- 2016 Mag Up -->
    2016MagUp:
    # <-- 2016 Mag Down -->
    2016MagDown:
  #  Pion
  # ------
  Pion:
    # <-- 2016 Mag Up -->
    2016MagUp:
    # <-- 2016 Mag Down -->
    2016MagDown:
  #  Kaon
  # ------
  Kaon:
    # <-- 2016 Mag Up -->
    2016MagUp:
    # <-- 2016 Mag Down -->
    2016MagDown:
  #  Proton
  # --------
  Proton:
    # <-- 2016 Mag Up -->
    2016MagUp:
    # <-- 2016 Mag Down -->
    2016MagDown:

# +------------------+
# |    GLOBAL PID    |
# +------------------+
GlobalPID:
  #  Muon
  # ------
  Muon:
    # <-- 2016 Mag Up -->
    2016MagUp:
    # <-- 2016 Mag Down -->
    2016MagDown:
  #  Pion
  # ------
  Pion:
    # <-- 2016 Mag Up -->
    2016MagUp:
    # <-- 2016 Mag Down -->
    2016MagDown:
  #  Kaon
  # ------
  Kaon:
    # <-- 2016 Mag Up -->
    2016MagUp:
    # <-- 2016 Mag Down -->
    2016MagDown:
  #  Proton
  # --------
  Proton:
    # <-- 2016 Mag Up -->
    2016MagUp:
    # <-- 2016 Mag Down -->
    2016MagDown:

# +----------------------+
# |    GLOBAL MUON ID    |
# +----------------------+
GlobalMuonId:
  #  Muon
  # ------
  Muon:
    # <-- 2016 Mag Up -->
    2016MagUp:
    # <-- 2016 Mag Down -->
    2016MagDown:
  #  Pion
  # ------
  Pion:
    # <-- 2016 Mag Up -->
    2016MagUp:
    # <-- 2016 Mag Down -->
    2016MagDown:
  #  Kaon
  # ------
  Kaon:
    # <-- 2016 Mag Up -->
    2016MagUp:
    # <-- 2016 Mag Down -->
    2016MagDown:
  #  Proton
  # --------
  Proton:
    # <-- 2016 Mag Up -->
    2016MagUp:
    # <-- 2016 Mag Down -->
    2016MagDown: