# +------------+
# |    RICH    |
# +------------+
Rich:
  #  Muon
  # ------
  Muon:
    # <-- 2016 Mag Up -->
    2016MagUp:
      chunk_size : 5000000   # 60 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      d_lr : 0.00002
      g_lr : 0.00002
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      lr_sched_factor : 0.915
      lr_sched_step : 4
      batch_size : 512
      num_epochs : 100
      validation_split : 0.2
    # <-- 2016 Mag Down -->
    2016MagDown:
  #  Pion
  # ------
  Pion:
    # <-- 2016 Mag Up -->
    2016MagUp:
      chunk_size : 5000000   # 150 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      d_lr : 0.00001
      g_lr : 0.00001
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      lr_sched_factor : 0.915
      lr_sched_step : 4
      batch_size : 512
      num_epochs : 100
      validation_split : 0.2
    # <-- 2016 Mag Down -->
    2016MagDown:
  #  Kaon
  # ------
  Kaon:
    # <-- 2016 Mag Up -->
    2016MagUp:
      chunk_size : 5000000   # 150 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      d_lr : 0.00003
      g_lr : 0.00003
      d_updt_per_batch : 2
      g_updt_per_batch : 1
      grad_penalty : 1.0
      lr_sched_factor : 0.900
      lr_sched_step : 4
      batch_size : 512
      num_epochs : 200
      validation_split : 0.2
    # <-- 2016 Mag Down -->
    2016MagDown:
  #  Proton
  # --------
  Proton:
    # <-- 2016 Mag Up -->
    2016MagUp:
      chunk_size : 5000000   # 105 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      d_lr : 0.00002
      g_lr : 0.00002
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      lr_sched_factor : 0.915
      lr_sched_step : 4
      batch_size : 512
      num_epochs : 100
      validation_split : 0.2
    # <-- 2016 Mag Down -->
    2016MagDown:

# +------------+
# |    MUON    |
# +------------+
Muon:
  #  Muon
  # ------
  Muon:
    # <-- 2016 Mag Up -->
    2016MagUp:
      chunk_size : 10000000   # 23 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      d_lr : 0.00002
      g_lr : 0.00002
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      lr_sched_factor : 0.915
      lr_sched_step : 4
      batch_size : 512
      num_epochs : 100
      validation_split : 0.2
    # <-- 2016 Mag Down -->
    2016MagDown:
  #  Pion
  # ------
  Pion:
    # <-- 2016 Mag Up -->
    2016MagUp:
      chunk_size :   # 2 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      d_lr : 0.00002
      g_lr : 0.00002
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      lr_sched_factor : 0.895
      lr_sched_step : 4
      batch_size : 256
      num_epochs : 100
      validation_split : 0.2
    # <-- 2016 Mag Down -->
    2016MagDown:
  #  Kaon
  # ------
  Kaon:
    # <-- 2016 Mag Up -->
    2016MagUp:
      chunk_size :   # 2 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      d_lr : 0.00002
      g_lr : 0.00002
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      lr_sched_factor : 0.895
      lr_sched_step : 3
      batch_size : 256
      num_epochs : 100
      validation_split : 0.2
    # <-- 2016 Mag Down -->
    2016MagDown:
  #  Proton
  # --------
  Proton:
    # <-- 2016 Mag Up -->
    2016MagUp:
      chunk_size :   # 5 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      d_lr : 0.00001
      g_lr : 0.00001
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      lr_sched_factor : 0.885
      lr_sched_step : 4
      batch_size : 512
      num_epochs : 100
      validation_split : 0.2
    # <-- 2016 Mag Down -->
    2016MagDown:

# +------------------+
# |    GLOBAL PID    |
# +------------------+
GlobalPID:
  #  Muon
  # ------
  Muon:
    # <-- 2016 Mag Up -->
    2016MagUp:
      chunk_size : 5000000   # 60 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      d_lr : 0.00002
      g_lr : 0.00002
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      lr_sched_factor : 0.900
      lr_sched_step : 4
      batch_size : 512
      num_epochs : 100
      validation_split : 0.2
    # <-- 2016 Mag Down -->
    2016MagDown:
  #  Pion
  # ------
  Pion:
    # <-- 2016 Mag Up -->
    2016MagUp:
      chunk_size : 5000000   # 150 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      d_lr : 0.00002
      g_lr : 0.00002
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      lr_sched_factor : 0.900
      lr_sched_step : 4
      batch_size : 512
      num_epochs : 100
      validation_split : 0.2
    # <-- 2016 Mag Down -->
    2016MagDown:
  #  Kaon
  # ------
  Kaon:
    # <-- 2016 Mag Up -->
    2016MagUp:
      chunk_size : 5000000   # 150 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      d_lr : 0.00002
      g_lr : 0.00002
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      lr_sched_factor : 0.900
      lr_sched_step : 4
      batch_size : 512
      num_epochs : 100
      validation_split : 0.2
    # <-- 2016 Mag Down -->
    2016MagDown:
  #  Proton
  # --------
  Proton:
    # <-- 2016 Mag Up -->
    2016MagUp:
      chunk_size : 5000000   # 105 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      d_lr : 0.00002
      g_lr : 0.00002
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      lr_sched_factor : 0.900
      lr_sched_step : 4
      batch_size : 512
      num_epochs : 100
      validation_split : 0.2
    # <-- 2016 Mag Down -->
    2016MagDown:

# +----------------------+
# |    GLOBAL MUON ID    |
# +----------------------+
GlobalMuonId:
  #  Muon
  # ------
  Muon:
    # <-- 2016 Mag Up -->
    2016MagUp:
      chunk_size : 10000000   # 23 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      d_lr : 0.00003
      g_lr : 0.00003
      d_updt_per_batch : 5
      g_updt_per_batch : 1
      grad_penalty : 1.0
      lr_sched_factor : 0.90
      lr_sched_step : 10
      batch_size : 512
      num_epochs : 200
      validation_split : 0.2
    # <-- 2016 Mag Down -->
    2016MagDown:
  #  Pion
  # ------
  Pion:
    # <-- 2016 Mag Up -->
    2016MagUp:
      chunk_size :   # 2 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      d_lr : 0.00003
      g_lr : 0.00003
      d_updt_per_batch : 5
      g_updt_per_batch : 1
      grad_penalty : 1.0
      lr_sched_factor : 0.90
      lr_sched_step : 10
      batch_size : 512
      num_epochs : 200
      validation_split : 0.2
    # <-- 2016 Mag Down -->
    2016MagDown:
  #  Kaon
  # ------
  Kaon:
    # <-- 2016 Mag Up -->
    2016MagUp:
      chunk_size :   # 2 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      d_lr : 0.00002
      g_lr : 0.00002
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      lr_sched_factor : 0.895
      lr_sched_step : 4
      batch_size : 256
      num_epochs : 100
      validation_split : 0.2
    # <-- 2016 Mag Down -->
    2016MagDown:
  #  Proton
  # --------
  Proton:
    # <-- 2016 Mag Up -->
    2016MagUp:
      chunk_size :   # 5 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      d_lr : 0.00002
      g_lr : 0.00002
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      lr_sched_factor : 0.895
      lr_sched_step : 4
      batch_size : 512
      num_epochs : 100
      validation_split : 0.2
    # <-- 2016 Mag Down -->
    2016MagDown:
