secrets_file: "config/secrets.yaml"
apptainer_image: harbor.cloud.infn.it/unpacked/lhcb-pidsim.sif
cvmfs_repo: /cvmfs/unpacked.infn.it
apptainer_cached_image: /tmp/lb-pidsim-train.sif

sample: 2016MU
storage_folder: tests
temp_dir: /tmp
training_time_limit_seconds: 60 #0
entries_for_validation: 10000 #00

nbconvert_args:
    - --allow-errors
    

training_data:
    - training-data/2016MU-sim10b/LamarrTraining-j109.0.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.1.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.10.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.100.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.101.root
other:

    - training-data/2016MU-sim10b/LamarrTraining-j109.102.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.103.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.104.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.105.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.106.root

    - training-data/2016MU-sim10b/LamarrTraining-j109.107.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.108.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.109.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.11.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.110.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.111.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.112.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.113.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.114.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.115.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.116.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.117.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.118.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.119.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.12.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.120.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.121.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.122.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.123.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.124.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.126.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.127.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.128.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.129.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.13.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.130.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.131.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.132.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.133.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.134.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.135.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.136.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.137.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.138.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.139.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.14.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.140.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.141.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.142.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.143.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.144.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.145.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.146.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.147.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.148.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.149.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.15.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.150.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.151.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.152.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.153.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.154.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.155.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.156.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.157.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.158.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.159.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.16.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.160.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.161.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.162.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.163.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.164.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.165.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.166.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.167.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.168.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.169.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.17.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.170.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.171.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.172.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.173.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.174.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.175.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.176.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.177.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.178.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.179.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.18.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.180.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.181.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.182.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.183.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.184.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.185.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.186.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.187.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.188.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.189.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.19.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.190.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.191.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.192.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.193.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.195.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.196.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.197.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.198.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.199.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.2.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.20.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.200.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.201.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.202.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.205.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.206.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.209.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.21.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.210.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.211.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.212.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.214.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.216.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.219.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.22.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.220.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.221.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.222.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.223.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.224.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.228.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.229.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.23.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.231.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.232.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.233.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.234.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.236.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.239.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.24.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.240.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.241.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.242.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.243.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.246.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.248.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.249.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.25.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.251.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.252.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.253.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.254.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.255.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.256.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.26.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.27.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.28.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.29.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.3.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.30.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.31.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.32.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.33.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.34.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.35.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.36.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.37.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.38.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.39.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.4.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.40.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.41.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.42.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.43.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.44.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.45.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.46.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.47.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.48.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.49.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.5.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.50.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.51.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.52.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.53.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.54.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.55.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.57.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.58.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.59.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.6.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.60.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.61.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.62.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.63.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.64.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.65.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.66.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.67.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.68.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.69.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.7.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.70.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.71.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.72.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.73.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.74.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.75.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.76.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.77.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.78.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.79.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.8.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.80.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.81.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.82.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.83.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.84.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.85.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.86.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.87.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.88.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.89.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.9.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.90.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.91.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.92.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.93.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.94.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.95.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.96.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.97.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.98.root
    - training-data/2016MU-sim10b/LamarrTraining-j109.99.root
