# +------------+
# |    RICH    |
# +------------+
Rich:
  #  Muon
  # ------
  Muon:
    # <-- 2016 Mag Up -->
    2016MagUp:
      chunk_size : 100000
      X_preprocessing : quantile
      Y_preprocessing : quantile
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.00001
      g_lr : 0.00001
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      batch_size : 500
      num_epochs : 10
      validation_split : 0.2
    # <-- 2016 Mag Down -->
    2016MagDown:
      chunk_size : 100000
      X_preprocessing : quantile
      Y_preprocessing : quantile
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.00001
      g_lr : 0.00001
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      batch_size : 500
      num_epochs : 10
      validation_split : 0.2
  #  Pion
  # ------
  Pion:
    # <-- 2016 Mag Up -->
    2016MagUp:
      chunk_size : 100000
      X_preprocessing : quantile
      Y_preprocessing : quantile
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.00001
      g_lr : 0.00001
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      batch_size : 500
      num_epochs : 10
      validation_split : 0.2
    # <-- 2016 Mag Down -->
    2016MagDown:
      chunk_size : 100000
      X_preprocessing : quantile
      Y_preprocessing : quantile
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.00001
      g_lr : 0.00001
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      batch_size : 500
      num_epochs : 10
      validation_split : 0.2
  #  Kaon
  # ------
  Kaon:
    # <-- 2016 Mag Up -->
    2016MagUp:
      chunk_size : 100000
      X_preprocessing : quantile
      Y_preprocessing : quantile
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.00001
      g_lr : 0.00001
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      batch_size : 500
      num_epochs : 10
      validation_split : 0.2
    # <-- 2016 Mag Down -->
    2016MagDown:
      chunk_size : 100000
      X_preprocessing : quantile
      Y_preprocessing : quantile
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.00001
      g_lr : 0.00001
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      batch_size : 500
      num_epochs : 10
      validation_split : 0.2
  #  Proton
  # --------
  Proton:
    # <-- 2016 Mag Up -->
    2016MagUp:
      chunk_size : 100000
      X_preprocessing : quantile
      Y_preprocessing : quantile
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.00001
      g_lr : 0.00001
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      batch_size : 500
      num_epochs : 10
      validation_split : 0.2
    # <-- 2016 Mag Down -->
    2016MagDown:
      chunk_size : 100000
      X_preprocessing : quantile
      Y_preprocessing : quantile
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.00001
      g_lr : 0.00001
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      batch_size : 500
      num_epochs : 10
      validation_split : 0.2

# +------------+
# |    MUON    |
# +------------+
Muon:
  #  Muon
  # ------
  Muon:
    # <-- 2016 Mag Up -->
    2016MagUp:
      chunk_size : 100000
      X_preprocessing : quantile
      Y_preprocessing : quantile
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.00001
      g_lr : 0.00001
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      batch_size : 500
      num_epochs : 10
      validation_split : 0.2
    # <-- 2016 Mag Down -->
    2016MagDown:
      chunk_size : 100000
      X_preprocessing : quantile
      Y_preprocessing : quantile
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.00001
      g_lr : 0.00001
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      batch_size : 500
      num_epochs : 10
      validation_split : 0.2
  #  Pion
  # ------
  Pion:
    # <-- 2016 Mag Up -->
    2016MagUp:
      chunk_size : 100000
      X_preprocessing : quantile
      Y_preprocessing : quantile
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.00001
      g_lr : 0.00001
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      batch_size : 500
      num_epochs : 10
      validation_split : 0.2
    # <-- 2016 Mag Down -->
    2016MagDown:
      chunk_size : 100000
      X_preprocessing : quantile
      Y_preprocessing : quantile
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.00001
      g_lr : 0.00001
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      batch_size : 500
      num_epochs : 10
      validation_split : 0.2
  #  Kaon
  # ------
  Kaon:
    # <-- 2016 Mag Up -->
    2016MagUp:
      chunk_size : 100000
      X_preprocessing : quantile
      Y_preprocessing : quantile
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.00001
      g_lr : 0.00001
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      batch_size : 500
      num_epochs : 10
      validation_split : 0.2
    # <-- 2016 Mag Down -->
    2016MagDown:
      chunk_size : 100000
      X_preprocessing : quantile
      Y_preprocessing : quantile
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.00001
      g_lr : 0.00001
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      batch_size : 500
      num_epochs : 10
      validation_split : 0.2
  #  Proton
  # --------
  Proton:
    # <-- 2016 Mag Up -->
    2016MagUp:
      chunk_size : 100000
      X_preprocessing : quantile
      Y_preprocessing : quantile
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.00001
      g_lr : 0.00001
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      batch_size : 500
      num_epochs : 10
      validation_split : 0.2
    # <-- 2016 Mag Down -->
    2016MagDown:
      chunk_size : 100000
      X_preprocessing : quantile
      Y_preprocessing : quantile
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.00001
      g_lr : 0.00001
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      batch_size : 500
      num_epochs : 10
      validation_split : 0.2

# +------------------+
# |    GLOBAL PID    |
# +------------------+
GlobalPID:
  #  Muon
  # ------
  Muon:
    # <-- 2016 Mag Up -->
    2016MagUp:
      chunk_size : 100000
      X_preprocessing : quantile
      Y_preprocessing : quantile
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.00001
      g_lr : 0.00001
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      batch_size : 500
      num_epochs : 10
      validation_split : 0.2
    # <-- 2016 Mag Down -->
    2016MagDown:
      chunk_size : 100000
      X_preprocessing : quantile
      Y_preprocessing : quantile
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.00001
      g_lr : 0.00001
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      batch_size : 500
      num_epochs : 10
      validation_split : 0.2
  #  Pion
  # ------
  Pion:
    # <-- 2016 Mag Up -->
    2016MagUp:
      chunk_size : 100000
      X_preprocessing : quantile
      Y_preprocessing : quantile
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.00001
      g_lr : 0.00001
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      batch_size : 500
      num_epochs : 10
      validation_split : 0.2
    # <-- 2016 Mag Down -->
    2016MagDown:
      chunk_size : 100000
      X_preprocessing : quantile
      Y_preprocessing : quantile
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.00001
      g_lr : 0.00001
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      batch_size : 500
      num_epochs : 10
      validation_split : 0.2
  #  Kaon
  # ------
  Kaon:
    # <-- 2016 Mag Up -->
    2016MagUp:
      chunk_size : 100000
      X_preprocessing : quantile
      Y_preprocessing : quantile
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.00001
      g_lr : 0.00001
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      batch_size : 500
      num_epochs : 10
      validation_split : 0.2
    # <-- 2016 Mag Down -->
    2016MagDown:
      chunk_size : 100000
      X_preprocessing : quantile
      Y_preprocessing : quantile
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.00001
      g_lr : 0.00001
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      batch_size : 500
      num_epochs : 10
      validation_split : 0.2
  #  Proton
  # --------
  Proton:
    # <-- 2016 Mag Up -->
    2016MagUp:
      chunk_size : 100000
      X_preprocessing : quantile
      Y_preprocessing : quantile
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.00001
      g_lr : 0.00001
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      batch_size : 500
      num_epochs : 10
      validation_split : 0.2
    # <-- 2016 Mag Down -->
    2016MagDown:
      chunk_size : 100000
      X_preprocessing : quantile
      Y_preprocessing : quantile
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.00001
      g_lr : 0.00001
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      batch_size : 500
      num_epochs : 10
      validation_split : 0.2

# +----------------------+
# |    GLOBAL MUON ID    |
# +----------------------+
GlobalMuonId:
  #  Muon
  # ------
  Muon:
    # <-- 2016 Mag Up -->
    2016MagUp:
      chunk_size : 100000
      X_preprocessing : quantile
      Y_preprocessing : quantile
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.00001
      g_lr : 0.00001
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      batch_size : 500
      num_epochs : 10
      validation_split : 0.2
    # <-- 2016 Mag Down -->
    2016MagDown:
      chunk_size : 100000
      X_preprocessing : quantile
      Y_preprocessing : quantile
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.00001
      g_lr : 0.00001
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      batch_size : 500
      num_epochs : 10
      validation_split : 0.2
  #  Pion
  # ------
  Pion:
    # <-- 2016 Mag Up -->
    2016MagUp:
      chunk_size : 100000
      X_preprocessing : quantile
      Y_preprocessing : quantile
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.00001
      g_lr : 0.00001
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      batch_size : 500
      num_epochs : 10
      validation_split : 0.2
    # <-- 2016 Mag Down -->
    2016MagDown:
      chunk_size : 100000
      X_preprocessing : quantile
      Y_preprocessing : quantile
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.00001
      g_lr : 0.00001
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      batch_size : 500
      num_epochs : 10
      validation_split : 0.2
  #  Kaon
  # ------
  Kaon:
    # <-- 2016 Mag Up -->
    2016MagUp:
      chunk_size : 100000
      X_preprocessing : quantile
      Y_preprocessing : quantile
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.00001
      g_lr : 0.00001
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      batch_size : 500
      num_epochs : 10
      validation_split : 0.2
    # <-- 2016 Mag Down -->
    2016MagDown:
      chunk_size : 100000
      X_preprocessing : quantile
      Y_preprocessing : quantile
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.00001
      g_lr : 0.00001
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      batch_size : 500
      num_epochs : 10
      validation_split : 0.2
  #  Proton
  # --------
  Proton:
    # <-- 2016 Mag Up -->
    2016MagUp:
      chunk_size : 100000
      X_preprocessing : quantile
      Y_preprocessing : quantile
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.00001
      g_lr : 0.00001
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      batch_size : 500
      num_epochs : 10
      validation_split : 0.2
    # <-- 2016 Mag Down -->
    2016MagDown:
      chunk_size : 100000
      X_preprocessing : quantile
      Y_preprocessing : quantile
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      critic_dim : 256
      d_lr : 0.00001
      g_lr : 0.00001
      d_updt_per_batch : 10
      g_updt_per_batch : 1
      grad_penalty : 1.0
      batch_size : 500
      num_epochs : 10
      validation_split : 0.2
