# +----------------------+
# |    DIRECTORY PATH    |
# +----------------------+

data_dir : 
  data   : /data
  simu   : /data

model_dir  : /models/opt_studies
class_dir  : /models/opt_studies
report_dir : /reports/opt_studies

hopaas :
  address : hopaas-server-address
  port    : 80   # or 443
  token   : user-hopaas-token
