# +------------+
# |    RICH    |
# +------------+
Rich:

  #  RICH : Muon
  # -------------
  Muon:
    2016-MagUp-data:
      - PIDCalib16_U_Jpsi_MuMTuple.root 
      - PIDCalib16_U_Jpsi_MuPTuple.root
    2016-MagUp-simu:
      - PIDSim16_U_incl_b_Mu.root
      - PIDSim16_U_Bd_JpsiX_Mu.root
      - PIDSim16_U_Bu_JpsiX_Mu.root
    2016-MagDown-data:
      - PIDCalib16_D_Jpsi_MuMTuple.root
      - PIDCalib16_D_Jpsi_MuPTuple.root

  #  RICH : Pion
  # -------------
  Pion:
    2016-MagUp-data:
      - PIDCalib16_U_DSt_PiPTuple.root
      - PIDCalib16_U_DSt_PiMTuple.root
    2016-MagUp-simu:
      - PIDSim16_U_incl_b_Pi.root
      - PIDSim16_U_Bd_JpsiX_Pi.root
      - PIDSim16_U_Bu_JpsiX_Pi.root
    2016-MagDown-data:
      - PIDCalib16_D_DSt_PiPTuple.root
      - PIDCalib16_D_DSt_PiMTuple.root

  #  RICH : Kaon
  # -------------
  Kaon:
    2016-MagUp-data:
      - PIDCalib16_U_DSt_KPTuple.root
      - PIDCalib16_U_DSt_KMTuple.root
    2016-MagUp-simu:
      - PIDSim16_U_incl_b_K.root
      - PIDSim16_U_Bd_JpsiX_K.root
      - PIDSim16_U_Bu_JpsiX_K.root
      - PIDSim16_U_Lb_etacpK_K.root
    2016-MagDown-data:
      - PIDCalib16_D_DSt_KPTuple.root
      - PIDCalib16_D_DSt_KMTuple.root

  #  RICH : Proton
  # ---------------
  Proton:
    2016-MagUp-data:
      - PIDCalib16_U_Lam0LL_PTuple.root
      - PIDCalib16_U_Lam0LL_PbarTuple.root
      - PIDCalib16_U_Lam0LL_HPT_PTuple.root
      - PIDCalib16_U_Lam0LL_HPT_PbarTuple.root
      - PIDCalib16_U_Lam0LL_VHPT_PTuple.root
      - PIDCalib16_U_Lam0LL_VHPT_PbarTuple.root
    2016-MagUp-simu:
      - PIDSim16_U_incl_b_P.root
      - PIDSim16_U_Bd_JpsiX_P.root
      - PIDSim16_U_Bu_JpsiX_P.root
      - PIDSim16_U_Lb_etacpK_P.root
    2016-MagDown-data:
      - PIDCalib16_D_Lam0LL_PTuple.root
      - PIDCalib16_D_Lam0LL_PbarTuple.root
      - PIDCalib16_D_Lam0LL_HPT_PTuple.root
      - PIDCalib16_D_Lam0LL_HPT_PbarTuple.root
      - PIDCalib16_D_Lam0LL_VHPT_PTuple.root
      - PIDCalib16_D_Lam0LL_VHPT_PbarTuple.root


# +------------+
# |    MUON    |
# +------------+
Muon:

  #  MUON : Muon
  # -------------
  Muon:
    2016-MagUp-data:
      - PIDCalib16_U_Jpsi_MuMTuple.root 
      - PIDCalib16_U_Jpsi_MuPTuple.root
    2016-MagUp-simu:
      - PIDSim16_U_incl_b_Mu.root
      - PIDSim16_U_Bd_JpsiX_Mu.root
      - PIDSim16_U_Bu_JpsiX_Mu.root
    2016-MagDown-data:
      - PIDCalib16_D_Jpsi_MuMTuple.root
      - PIDCalib16_D_Jpsi_MuPTuple.root

  #  MUON : Pion
  # -------------
  Pion:
    2016-MagUp-data:
      - PIDCalib16_U_DSt_PiPTuple.root
      - PIDCalib16_U_DSt_PiMTuple.root
    2016-MagUp-simu:
      - PIDSim16_U_incl_b_Pi.root
      - PIDSim16_U_Bd_JpsiX_Pi.root
      - PIDSim16_U_Bu_JpsiX_Pi.root
    2016-MagDown-data:
      - PIDCalib16_D_DSt_PiPTuple.root
      - PIDCalib16_D_DSt_PiMTuple.root

  #  MUON : Kaon
  # -------------
  Kaon:
    2016-MagUp-data:
      - PIDCalib16_U_DSt_KPTuple.root
      - PIDCalib16_U_DSt_KMTuple.root
    2016-MagUp-simu:
      - PIDSim16_U_incl_b_K.root
      - PIDSim16_U_Bd_JpsiX_K.root
      - PIDSim16_U_Bu_JpsiX_K.root
      - PIDSim16_U_Lb_etacpK_K.root
    2016-MagDown-data:
      - PIDCalib16_D_DSt_KPTuple.root
      - PIDCalib16_D_DSt_KMTuple.root

  #  MUON : Proton
  # ---------------
  Proton:
    2016-MagUp-data:
      - PIDCalib16_U_Lam0LL_P_isMuonTuple.root
      - PIDCalib16_U_Lam0LL_Pbar_isMuonTuple.root
    2016-MagUp-simu:
      - PIDSim16_U_incl_b_P.root
      - PIDSim16_U_Bd_JpsiX_P.root
      - PIDSim16_U_Bu_JpsiX_P.root
      - PIDSim16_U_Lb_etacpK_P.root
    2016-MagDown-data:
      - PIDCalib16_D_Lam0LL_P_isMuonTuple.root
      - PIDCalib16_D_Lam0LL_Pbar_isMuonTuple.root


# +------------------+
# |    GLOBAL PID    |
# +------------------+
GlobalPID:

  #  GLOBAL PID : Muon
  # -------------------
  Muon:
    2016-MagUp-data:
      - PIDCalib16_U_Jpsi_MuMTuple.root 
      - PIDCalib16_U_Jpsi_MuPTuple.root
    2016-MagUp-simu:
      - PIDSim16_U_incl_b_Mu.root
      - PIDSim16_U_Bd_JpsiX_Mu.root
      - PIDSim16_U_Bu_JpsiX_Mu.root
    2016-MagDown-data:
      - PIDCalib16_D_Jpsi_MuMTuple.root
      - PIDCalib16_D_Jpsi_MuPTuple.root

  #  GLOBAL PID : Pion
  # -------------------
  Pion:
    2016-MagUp-data:
      - PIDCalib16_U_DSt_PiPTuple.root
      - PIDCalib16_U_DSt_PiMTuple.root
    2016-MagUp-simu:
      - PIDSim16_U_incl_b_Pi.root
      - PIDSim16_U_Bd_JpsiX_Pi.root
      - PIDSim16_U_Bu_JpsiX_Pi.root
    2016-MagDown-data:
      - PIDCalib16_D_DSt_PiPTuple.root
      - PIDCalib16_D_DSt_PiMTuple.root

  #  GLOBAL PID : Kaon
  # -------------------
  Kaon:
    2016-MagUp-data:
      - PIDCalib16_U_DSt_KPTuple.root
      - PIDCalib16_U_DSt_KMTuple.root
    2016-MagUp-simu:
      - PIDSim16_U_incl_b_K.root
      - PIDSim16_U_Bd_JpsiX_K.root
      - PIDSim16_U_Bu_JpsiX_K.root
      - PIDSim16_U_Lb_etacpK_K.root
    2016-MagDown-data:
      - PIDCalib16_D_DSt_KPTuple.root
      - PIDCalib16_D_DSt_KMTuple.root

  #  GLOBAL PID : Proton
  # ---------------------
  Proton:
    2016-MagUp-data:
      - PIDCalib16_U_Lam0LL_PTuple.root
      - PIDCalib16_U_Lam0LL_PbarTuple.root
      - PIDCalib16_U_Lam0LL_HPT_PTuple.root
      - PIDCalib16_U_Lam0LL_HPT_PbarTuple.root
      - PIDCalib16_U_Lam0LL_VHPT_PTuple.root
      - PIDCalib16_U_Lam0LL_VHPT_PbarTuple.root
    2016-MagUp-simu:
      - PIDSim16_U_incl_b_P.root
      - PIDSim16_U_Bd_JpsiX_P.root
      - PIDSim16_U_Bu_JpsiX_P.root
      - PIDSim16_U_Lb_etacpK_P.root
    2016-MagDown-data:
      - PIDCalib16_D_Lam0LL_PTuple.root
      - PIDCalib16_D_Lam0LL_PbarTuple.root
      - PIDCalib16_D_Lam0LL_HPT_PTuple.root
      - PIDCalib16_D_Lam0LL_HPT_PbarTuple.root
      - PIDCalib16_D_Lam0LL_VHPT_PTuple.root
      - PIDCalib16_D_Lam0LL_VHPT_PbarTuple.root


# +----------------------+
# |    GLOBAL MUON ID    |
# +----------------------+
GlobalMuonId:

  #  GLOBAL MUON ID : Muon
  # -----------------------
  Muon:
    2016-MagUp-data:
      - PIDCalib16_U_Jpsi_MuMTuple.root 
      - PIDCalib16_U_Jpsi_MuPTuple.root
    2016-MagUp-simu:
      - PIDSim16_U_incl_b_Mu.root
      - PIDSim16_U_Bd_JpsiX_Mu.root
      - PIDSim16_U_Bu_JpsiX_Mu.root
    2016-MagDown-data:
      - PIDCalib16_D_Jpsi_MuMTuple.root
      - PIDCalib16_D_Jpsi_MuPTuple.root

  #  GLOBAL MUON ID : Pion
  # -----------------------
  Pion:
    2016-MagUp-data:
      - PIDCalib16_U_DSt_PiPTuple.root
      - PIDCalib16_U_DSt_PiMTuple.root
    2016-MagUp-simu:
      - PIDSim16_U_incl_b_Pi.root
      - PIDSim16_U_Bd_JpsiX_Pi.root
      - PIDSim16_U_Bu_JpsiX_Pi.root
    2016-MagDown-data:
      - PIDCalib16_D_DSt_PiPTuple.root
      - PIDCalib16_D_DSt_PiMTuple.root

  #  GLOBAL MUON ID : Kaon
  # -----------------------
  Kaon:
    2016-MagUp-data:
      - PIDCalib16_U_DSt_KPTuple.root
      - PIDCalib16_U_DSt_KMTuple.root
    2016-MagUp-simu:
      - PIDSim16_U_incl_b_K.root
      - PIDSim16_U_Bd_JpsiX_K.root
      - PIDSim16_U_Bu_JpsiX_K.root
      - PIDSim16_U_Lb_etacpK_K.root
    2016-MagDown-data:
      - PIDCalib16_D_DSt_KPTuple.root
      - PIDCalib16_D_DSt_KMTuple.root

  #  GLOBAL MUON ID : Proton
  # -------------------------
  Proton:
    2016-MagUp-data:
      - PIDCalib16_U_Lam0LL_P_isMuonTuple.root
      - PIDCalib16_U_Lam0LL_Pbar_isMuonTuple.root
    2016-MagUp-simu:
      - PIDSim16_U_incl_b_P.root
      - PIDSim16_U_Bd_JpsiX_P.root
      - PIDSim16_U_Bu_JpsiX_P.root
      - PIDSim16_U_Lb_etacpK_P.root
    2016-MagDown-data:
      - PIDCalib16_D_Lam0LL_P_isMuonTuple.root
      - PIDCalib16_D_Lam0LL_Pbar_isMuonTuple.root


# +---------------+
# |    IS MUON    |
# +---------------+
isMuon:

  #  IS MUON : Muon
  # ----------------
  Muon:
    2016-MagUp-data:
      - PIDCalib16_U_Jpsi_MuMTuple.root 
      - PIDCalib16_U_Jpsi_MuPTuple.root
    2016-MagUp-simu:
      - PIDSim16_U_incl_b_Mu.root
      - PIDSim16_U_Bd_JpsiX_Mu.root
      - PIDSim16_U_Bu_JpsiX_Mu.root
    2016-MagDown-data:
      - PIDCalib16_D_Jpsi_MuMTuple.root
      - PIDCalib16_D_Jpsi_MuPTuple.root

  #  IS MUON : Pion
  # ----------------
  Pion:
    2016-MagUp-data:
      - PIDCalib16_U_DSt_PiPTuple.root
      - PIDCalib16_U_DSt_PiMTuple.root
    2016-MagUp-simu:
      - PIDSim16_U_incl_b_Pi.root
      - PIDSim16_U_Bd_JpsiX_Pi.root
      - PIDSim16_U_Bu_JpsiX_Pi.root
    2016-MagDown-data:
      - PIDCalib16_D_DSt_PiPTuple.root
      - PIDCalib16_D_DSt_PiMTuple.root

  #  IS MUON : Kaon
  # ----------------
  Kaon:
    2016-MagUp-data:
      - PIDCalib16_U_DSt_KPTuple.root
      - PIDCalib16_U_DSt_KMTuple.root
    2016-MagUp-simu:
      - PIDSim16_U_incl_b_K.root
      - PIDSim16_U_Bd_JpsiX_K.root
      - PIDSim16_U_Bu_JpsiX_K.root
      - PIDSim16_U_Lb_etacpK_K.root
    2016-MagDown-data:
      - PIDCalib16_D_DSt_KPTuple.root
      - PIDCalib16_D_DSt_KMTuple.root

  #  IS MUON : Proton
  # ------------------
  Proton:
    2016-MagUp-data:
      - PIDCalib16_U_Lam0LL_PTuple.root
      - PIDCalib16_U_Lam0LL_PbarTuple.root
      - PIDCalib16_U_Lam0LL_HPT_PTuple.root
      - PIDCalib16_U_Lam0LL_HPT_PbarTuple.root
      - PIDCalib16_U_Lam0LL_VHPT_PTuple.root
      - PIDCalib16_U_Lam0LL_VHPT_PbarTuple.root
    2016-MagUp-simu:
      - PIDSim16_U_incl_b_P.root
      - PIDSim16_U_Bd_JpsiX_P.root
      - PIDSim16_U_Bu_JpsiX_P.root
      - PIDSim16_U_Lb_etacpK_P.root
    2016-MagDown-data:
      - PIDCalib16_D_Lam0LL_PTuple.root
      - PIDCalib16_D_Lam0LL_PbarTuple.root
      - PIDCalib16_D_Lam0LL_HPT_PTuple.root
      - PIDCalib16_D_Lam0LL_HPT_PbarTuple.root
      - PIDCalib16_D_Lam0LL_VHPT_PTuple.root
      - PIDCalib16_D_Lam0LL_VHPT_PbarTuple.root
      