# ==========================================================================================
with-weights:
# ==========================================================================================

  # +------------+
  # |    MUON    |
  # +------------+
  Muon:

    # <---- | Calib samples | 2016 Mag Up | ---->
    2016-MagUp-data:
      chunk_size : 1000000   # 60 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      d_lr : 0.00005
      g_lr : 0.00005
      d_updt_per_batch : 2
      g_updt_per_batch : 1
      v_adv_dir_updt : 1
      adv_lp_penalty : 100.0
      lr_sched_factor : 0.90
      lr_sched_step : 10
      batch_size : 512
      num_epochs : 500
      validation_split : 0.2

    # <---- | Calib samples | 2016 Mag Down | ---->
    2016-MagDown-data:

  # +------------+
  # |    PION    |
  # +------------+
  Pion:

    # <---- | Calib samples | 2016 Mag Up | ---->
    2016-MagUp-data:
      chunk_size : 1000000   # 150 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      d_lr : 0.00005
      g_lr : 0.00005
      d_updt_per_batch : 2
      g_updt_per_batch : 1
      v_adv_dir_updt : 1
      adv_lp_penalty : 100.0
      lr_sched_factor : 0.90
      lr_sched_step : 10
      batch_size : 512
      num_epochs : 500
      validation_split : 0.2

    # <---- | Calib samples | 2016 Mag Down | ---->
    2016-MagDown-data:

  # +------------+
  # |    KAON    |
  # +------------+
  Kaon:

    # <---- | Calib samples | 2016 Mag Up | ---->
    2016-MagUp-data:
      chunk_size : 1000000   # 150 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      d_lr : 0.00005
      g_lr : 0.00005
      d_updt_per_batch : 2
      g_updt_per_batch : 1
      v_adv_dir_updt : 1
      adv_lp_penalty : 100.0
      lr_sched_factor : 0.90
      lr_sched_step : 10
      batch_size : 512
      num_epochs : 500
      validation_split : 0.2

    # <---- | Calib samples | 2016 Mag Down | ---->
    2016-MagDown-data:

  # +--------------+
  # |    PROTON    |
  # +--------------+
  Proton:
    # <---- | Calib samples | 2016 Mag Up | ---->
    2016-MagUp-data:
      chunk_size : 1000000   # 105 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      d_lr : 0.00005
      g_lr : 0.00005
      d_updt_per_batch : 2
      g_updt_per_batch : 1
      v_adv_dir_updt : 1
      adv_lp_penalty : 100.0
      lr_sched_factor : 0.90
      lr_sched_step : 10
      batch_size : 512
      num_epochs : 500
      validation_split : 0.2
    
    # <---- | Calib samples | 2016 Mag Down | ---->
    2016-MagDown-data:

# ==========================================================================================
no-weights:
# ==========================================================================================

  # +------------+
  # |    MUON    |
  # +------------+
  Muon:

    # <---- | Calib samples | 2016 Mag Up | ---->
    2016-MagUp-data:
      chunk_size : 1000000   # 60 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      d_lr : 0.00005
      g_lr : 0.00005
      d_updt_per_batch : 2
      g_updt_per_batch : 1
      v_adv_dir_updt : 1
      adv_lp_penalty : 100.0
      lr_sched_factor : 0.90
      lr_sched_step : 10
      batch_size : 512
      num_epochs : 500
      validation_split : 0.2

    # <---- | Simu samples | 2016 Mag Up | ---->
    2016-MagUp-simu:
      chunk_size : 1000000   # 18 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      d_lr : 0.00005
      g_lr : 0.00005
      d_updt_per_batch : 2
      g_updt_per_batch : 1
      v_adv_dir_updt : 1
      adv_lp_penalty : 100.0
      lr_sched_factor : 0.90
      lr_sched_step : 10
      batch_size : 512
      num_epochs : 500
      validation_split : 0.2

    # <---- | Calib samples | 2016 Mag Down | ---->
    2016-MagDown-data:

    # <---- | Simu samples | 2016 Mag Down | ---->
    2016-MagDown-simu:

  # +------------+
  # |    PION    |
  # +------------+
  Pion:

    # <---- | Calib samples | 2016 Mag Up | ---->
    2016-MagUp-data:
      chunk_size : 1000000   # 150 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      d_lr : 0.00005
      g_lr : 0.00005
      d_updt_per_batch : 2
      g_updt_per_batch : 1
      v_adv_dir_updt : 1
      adv_lp_penalty : 100.0
      lr_sched_factor : 0.90
      lr_sched_step : 10
      batch_size : 512
      num_epochs : 500
      validation_split : 0.2

    # <---- | Simu samples | 2016 Mag Up | ---->
    2016-MagUp-simu:
      chunk_size : 1000000   # 150 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      d_lr : 0.00005
      g_lr : 0.00005
      d_updt_per_batch : 2
      g_updt_per_batch : 1
      v_adv_dir_updt : 1
      adv_lp_penalty : 100.0
      lr_sched_factor : 0.90
      lr_sched_step : 10
      batch_size : 512
      num_epochs : 500
      validation_split : 0.2

    # <---- | Calib samples | 2016 Mag Down | ---->
    2016-MagDown-data:

    # <---- | Simu samples | 2016 Mag Down | ---->
    2016-MagDown-simu:

  # +------------+
  # |    KAON    |
  # +------------+
  Kaon:

    # <---- | Calib samples | 2016 Mag Up | ---->
    2016-MagUp-data:
      chunk_size : 1000000   # 150 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      d_lr : 0.00005
      g_lr : 0.00005
      d_updt_per_batch : 2
      g_updt_per_batch : 1
      v_adv_dir_updt : 1
      adv_lp_penalty : 100.0
      lr_sched_factor : 0.90
      lr_sched_step : 10
      batch_size : 512
      num_epochs : 500
      validation_split : 0.2

    # <---- | Simu samples | 2016 Mag Up | ---->
    2016-MagUp-simu:
      chunk_size : 1000000   # 40 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      d_lr : 0.00005
      g_lr : 0.00005
      d_updt_per_batch : 2
      g_updt_per_batch : 1
      v_adv_dir_updt : 1
      adv_lp_penalty : 100.0
      lr_sched_factor : 0.90
      lr_sched_step : 10
      batch_size : 512
      num_epochs : 500
      validation_split : 0.2

    # <---- | Calib samples | 2016 Mag Down | ---->
    2016-MagDown-data:

    # <---- | Simu samples | 2016 Mag Down | ---->
    2016-MagDown-simu:

  # +--------------+
  # |    PROTON    |
  # +--------------+
  Proton:
    # <---- | Calib samples | 2016 Mag Up | ---->
    2016-MagUp-data:
      chunk_size : 1000000   # 105 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      d_lr : 0.00005
      g_lr : 0.00005
      d_updt_per_batch : 2
      g_updt_per_batch : 1
      v_adv_dir_updt : 1
      adv_lp_penalty : 100.0
      lr_sched_factor : 0.90
      lr_sched_step : 10
      batch_size : 512
      num_epochs : 500
      validation_split : 0.2
    
    # <---- | Simu samples | 2016 Mag Up | ---->
    2016-MagUp-simu:
      chunk_size : 1000000   # 30 mln
      d_num_layers  : 5
      d_num_nodes   : 128
      d_alpha_leaky : 0.05
      g_num_layers  : 5
      g_num_nodes   : 128
      g_alpha_leaky : 0.05
      latent_dim : 64
      d_lr : 0.00005
      g_lr : 0.00005
      d_updt_per_batch : 2
      g_updt_per_batch : 1
      v_adv_dir_updt : 1
      adv_lp_penalty : 100.0
      lr_sched_factor : 0.90
      lr_sched_step : 10
      batch_size : 512
      num_epochs : 500
      validation_split : 0.2

    # <---- | Calib samples | 2016 Mag Down | ---->
    2016-MagDown-data:

    # <---- | Simu samples | 2016 Mag Down | ---->
    2016-MagDown-simu: