name: Train models

on:
  pull_request:
    branches:
      - main

concurrency:
  group: pull_request-${{ github.head_ref }}
  cancel-in-progress: true


jobs:
    pid-2016MagUp-Sim10b:
        uses: LamarrSim/release-models/.github/workflows/release.yaml@main
        permissions:
          contents: write
          pull-requests: write
        with:
            name: pp-2016-MU-Sim10b-${{ github.head_ref }}
            snakemake_dir: pidgan
            target: cache_container validate_all
            main_runner: aiinfn-lamarrsim-4gpus
            model_prefix: pid
            additional_config: |
                storage_folder: pid-2016MagUp-Sim10b

            additional_profile: |
                jobs: 4
                cores: 32

                resources:
                  mem_mb: 500000
                  millicpu: 32000
                  gpu: 4

            generated_model_path: /tmp/compiled_model.c
        secrets:
            SECRETS_YAML: ${{ secrets.STORAGE_SECRETS }}

