name: Train models

on:
  pull_request:
    branches:
      - main

concurrency:
  group: pull_request-${{ github.head_ref }}
  cancel-in-progress: true


jobs:
    trk-2016MagUp-Sim10b:
        uses: LamarrSim/release-models/.github/workflows/release.yaml@main
        permissions:
          contents: write
          pull-requests: write
        with:
            name: pp-2016-MU-Sim10b-${{ github.head_ref }}
            snakemake_dir: pidgan
            target: cache_container validate_all
            additional_config: ""
            additional_profile: ""
            generated_model_path: /tmp/compiled_pid_model.c
        secrets:
            SECRETS_YAML: ${{ secrets.STORAGE_SECRETS }}

